name: Publish to JSR

on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish

      - name: Get Version from README
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=^## Version\n\nv)[0-9]+\.[0-9]+\.[0-9]+' README.md | head -1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "::set-output name=VERSION::$VERSION"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: "Release ${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false
          body: $(cat README.md | sed -n '/## Version/,/##/p')
